namespace Cod3rsGrowth.Dominio.Enums
{
    public enum Genero
    {
        Acao,
        ArtesMarciais,
        Aventura,
        Comedia,
        Drama,
        Ecchi,
        Espaco,
        Esporte,
        Fantasia,
        Harem,
        Historico,
        Horror,
        Jogos,
        MahouShoujo,
        Mecha,
        Militar,
        Misterio,
        Musical,
        Psicologico,
        Romance,
        Samurai,
        SciFi,
        Seinen,
        Shoujo,
        Shounen,
        SliceOfLife,
        Sobrenatural,
        VidaEscolar,
        Yaoi,
        Yuri
    };
}
